### ISSUE TITLE
ENV variable for mail setting 

### ISSUE THREAD

**Issue by vot4anto** [kkoralsky/tmate-docker-compose#2]
Thanks a lot for you compose files, i do a little modification to it:

```
version: '3.7'

networks:
  tmate:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 192.168.238.0/24

volumes:
  pg_data:

# yaml template 
x-op-service-default: &service_default
  restart: unless-stopped
  init: true

services:

  master:
    <<: *service_default
    image: tmate/tmate-master:latest
    environment:
      HOSTNAME: master-0
      MASTER_BASE_URL: &master_base_url 'http://${EXTERNAL_FQDN}:4000/'
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      INTERNAL_API_AUTH_TOKEN: &internal_api_auth_token ${INTERNAL_API_AUTH_TOKEN}
      PG_URI: pg://tmate:${POSTGRES_PASSWORD}@postgres:5432/tmate
      # PG_POOLSIZE:
      # PG_SSL_CA_CERT:
      ERL_NODE_NAME: erl_node_name
      ERL_COOKIE: erl_cookie
      MAILGUN_API_KEY: mailgun_api_key
      MAILGUN_DOMAIN: openquake.org
    networks:
      tmate:
    ports: ["0.0.0.0:4000:4000"]
    depends_on:
      - "postgres"

  ssh:
    <<: *service_default
    image: tmate/tmate-ssh-server:latest
    environment:
      SSH_KEYS_PATH: /keys
      HAS_WEBSOCKET: 1
      SSH_HOSTNAME: ${EXTERNAL_FQDN}
      SSH_PORT_LISTEN: 222
      SSH_PORT_ADVERTISE: 222
    command:
      # - -a/keys/authorized_keys
      - -wwebsocket
      - -p 222
    volumes: ["$PWD/keys:/keys"]
    networks:
      tmate:
    ports: ["0.0.0.0:222:222"]
    cap_add: [SYS_ADMIN]

  websocket:
    <<: *service_default
    image: tmate/tmate-websocket:latest
    environment:
      WEBSOCKET_BASE_URL: 'ws://${EXTERNAL_FQDN}:4001/'
      MASTER_BASE_URL: http://master:4000/
      USER_FACING_BASE_URL: *master_base_url
      DAEMON_HMAC_KEY: ${DAEMON_HMAC_KEY} 
      INTERNAL_API_AUTH_TOKEN: *internal_api_auth_token
      ERL_NODE_NAME: erl_node_name
      ERL_COOKIE: erl_cookie
    expose: [4002]
    networks:
      tmate:
    ports: ["0.0.0.0:4001:4001"]

  postgres:
    <<: *service_default
    image: postgres:10
    environment:
      POSTGRES_USER: tmate
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: tmate
    networks:
      tmate:
    volumes:
        - "pg_data:/var/lib/postgresql/data:rw"

```
Can you please tell me where I can find the ENV for the image: tmate/tmate-master:latest because I want to enable the Email API Key from web panel, but I have an Internal Server Error because infact I had'n configure nothing about domain name, smtp, authentication for sent mail.

Thanks
